export const teas = {
    START_FETCH_TEAS: 'START_FETCH_TEAS',
    SET_FETCH_TEAS: 'SET_FETCH_TEAS',
    ERROR_FETCH_TEAS: 'ERROR_FETCH_TEAS',
    START_SUBMIT_TEA: 'START_SUBMIT_TEA',
    FINISH_SUBMIT_TEA: 'FINISH_SUBMIT_TEA',
};

export const userTeas = {
    START_FETCH_USER_TEAS: 'START_FETCH_USER_TEAS',
    SET_FETCH_USER_TEAS: 'SET_FETCH_USER_TEAS',
};